apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  # volume can be mounted by only one node at a time
  accessModes:
    - ReadWriteOnce
  resources:
  # storage required for mounting nginx and prometheus containers
    requests:
      storage: 2Gi
  # name of the storageclass
  storageClassName: ebs-sc