apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-ebs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Ensures the volume can be mounted by only one node at a time
  persistentVolumeReclaimPolicy: Retain  # What happens to the volume after PVC deletion
  storageClassName: ebs-sc  # Storage class that specifies EBS
  csi:
    driver: ebs.csi.aws.com  # AWS EBS CSI Driver
    volumeHandle: <volume-id>  # The ID of the existing EBS volume