apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-ebs-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  # volume can be mounted by only one node at a time
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain
  # name of the storage class created for ebs
  storageClassName: ebs-sc
  csi:
    # ebs driver name
    driver: ebs.csi.aws.com
    # volume id of ebs
    volumeHandle: <volume-id>