apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # Scrape metrics every 15 seconds

    scrape_configs:
      - job_name: 'nginx'
        static_configs:
          - targets: ['nginx-service:80']