apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s # 15 seconds interval for scrapping

    scrape_configs:
      - job_name: 'nginx'
        static_configs:
          - targets: ['nginx-service:80'] # service and port of nginx